### ISSUE TITLE
not available

### ISSUE THREAD

**Issue by TAOTAOMIX** [Acly/comfyui-tooling-nodes#12]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\custom_nodes\comfyui-tooling-nodes\nodes.py", line 20, in load_image
    img = Image.open(BytesIO(imgdata))
  File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\python\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002AB9549C090>

Prompt executed in 0.01 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
------------------------
Fault Traceback: 
Not Available

Error occurred when executing ETN_LoadImageBase64:

cannot identify image file <_io.BytesIO object at 0x000002AB976583B0>

File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\custom_nodes\comfyui-tooling-nodes\nodes.py", line 20, in load_image
img = Image.open(BytesIO(imgdata))
File "D:\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\python\lib\site-packages\PIL\Image.py", line 3298, in open
raise UnidentifiedImageError(msg)

关闭

**Comment by Shiyao-Huang** [comment]
please change the  seed 。
